{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-sa
  namespace: my-app1
  labels:
    owner: helm-chart
  annotations:
       eks.amazonaws.com/role-arn: "arn:aws:iam::471112523246:role/my-role"
{{- end }}
